server:
  port: 16000
spring:
  servlet:
    multipart:
      enabled: true
  profiles:
    active: postgres
  application:
    name: bct-server
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  data:
    rest:
      detection-strategy: annotated
settings:
  timezone: Asia/Shanghai
  secret: dkJ34Bdadf098adf
  issuer: tongyu.tech
  env: ${ENV:dev}


---
# postgres
spring:
  profiles: postgres
  datasource:
    platform: postgres
    url: jdbc:postgresql://${POSTGRES_HOST:192.168.187.130}:${POSTGRES_PORT:5432}/bct?characterEncoding=UTF-8&stringtype=unspecified
    username: bct
    password: kEaLJ9ZERLLN
    initialization-mode: always
  jpa:
    properties:
      generate-ddl: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        ddl-auto: update
